---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-cruddeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mvc-crud
  template: 
    metadata:
      name: mvc-crudpod
      labels:
        app: mvc-crud
    spec:
      containers:
      - name: mvc-crudcontainer
        image: bhushanghodke1500/mvc-crud
        ports:
          - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-crudsvc
spec:
  type: NodePort
  selector:
    app: mvc-crud
  ports:
    - port: 80
      targetPort: 4040
      nodePort: 30785
...